# Generated by Django 2.2.9 on 2020-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('availableDate', models.DateField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
